name = "flights-tracker-worker"
main = "src/workers/index.ts"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat", "nodejs_als", "nodejs_compat_populate_process_env"]

# Keep workers.dev subdomain
workers_dev = true

# Custom domain routing
[[routes]]
pattern = "workers.graypane.com"
custom_domain = true

# Observability
[observability]
enabled = true
head_sampling_rate = 1
upload_source_maps = true

# Cron trigger - every 6 hours
[triggers]
crons = ["0 */6 * * *"]

# Version metadata
[version_metadata]
binding = "CF_VERSION_METADATA"

# Workflow bindings
[[workflows]]
name = "check-flight-alerts"
binding = "CHECK_ALERTS_WORKFLOW"
class_name = "CheckFlightAlertsWorkflow"

[[workflows]]
name = "process-flight-alerts"
binding = "PROCESS_ALERTS_WORKFLOW"
class_name = "ProcessFlightAlertsWorkflow"

[[workflows]]
name = "seats-aero-search"
binding = "SEATS_AERO_SEARCH_WORKFLOW"
class_name = "ProcessSeatsAeroSearchWorkflow"

# Queue configuration
[[queues.producers]]
queue = "flights-tracker-alerts-queue"
binding = "ALERTS_QUEUE"

[[queues.consumers]]
queue = "flights-tracker-alerts-queue"
max_batch_size = 10
max_batch_timeout = 30
max_concurrency = 10  # Critical: limit to 10 concurrent users
max_retries = 3
