name: CI/CD

on:
  pull_request:
  push:
    branches: [ main ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint_format:
    name: Lint and Format
    uses: ./.github/workflows/lint-format.yml

  build:
    name: Build
    needs: [lint_format]
    runs-on: ubuntu-latest
    steps:
      - run: echo "placeholder step to enable job fan-out" # GitHub requires at least one step

  worker_build:
    name: Worker Build (Dry Run)
    needs: [build]
    uses: ./.github/workflows/worker-build.yml
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      SEATS_AERO_API_KEY: ${{ secrets.SEATS_AERO_API_KEY }}
      WORKER_URL: ${{ secrets.WORKER_URL }}
      WORKER_API_KEY: ${{ secrets.WORKER_API_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
      NEXT_PUBLIC_MAPKIT_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPKIT_TOKEN }}

  web_build:
    name: Web App Build
    needs: [build]
    uses: ./.github/workflows/web-build.yml
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      SEATS_AERO_API_KEY: ${{ secrets.SEATS_AERO_API_KEY }}
      WORKER_URL: ${{ secrets.WORKER_URL }}
      WORKER_API_KEY: ${{ secrets.WORKER_API_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
      NEXT_PUBLIC_MAPKIT_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPKIT_TOKEN }}

  migrate_db:
    name: Database Migrate (main only)
    if: github.ref == 'refs/heads/main'
    needs: [web_build, worker_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.30
      - run: bun install --frozen-lockfile
      - name: Run migrations
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: bun run db:migrate

  migrate_dry_run:
    name: Database Migration Dry-Run (PRs)
    if: github.event_name == 'pull_request'
    needs: [web_build, worker_build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.30
      - run: bun install --frozen-lockfile
      - name: Drizzle schema check
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: npx drizzle-kit check

  tests:
    name: Tests
    needs: [web_build, worker_build]
    runs-on: ubuntu-latest
    steps:
      - run: echo "placeholder step to enable job fan-out"

  app_tests:
    name: App Tests
    needs: [tests]
    uses: ./.github/workflows/app-tests.yml
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      SEATS_AERO_API_KEY: ${{ secrets.SEATS_AERO_API_KEY }}
      WORKER_URL: ${{ secrets.WORKER_URL }}
      WORKER_API_KEY: ${{ secrets.WORKER_API_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
      NEXT_PUBLIC_MAPKIT_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPKIT_TOKEN }}

  worker_tests:
    name: Worker Tests
    needs: [tests]
    uses: ./.github/workflows/worker-tests.yml
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      SEATS_AERO_API_KEY: ${{ secrets.SEATS_AERO_API_KEY }}
      WORKER_URL: ${{ secrets.WORKER_URL }}
      WORKER_API_KEY: ${{ secrets.WORKER_API_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
      NEXT_PUBLIC_MAPKIT_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPKIT_TOKEN }}

  fli_tests:
    name: Fli Tests
    needs: [tests]
    uses: ./.github/workflows/fli-tests.yml
    secrets:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      SUPABASE_SECRET_KEY: ${{ secrets.SUPABASE_SECRET_KEY }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      SEATS_AERO_API_KEY: ${{ secrets.SEATS_AERO_API_KEY }}
      WORKER_URL: ${{ secrets.WORKER_URL }}
      WORKER_API_KEY: ${{ secrets.WORKER_API_KEY }}
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY }}
      NEXT_PUBLIC_MAPKIT_TOKEN: ${{ secrets.NEXT_PUBLIC_MAPKIT_TOKEN }}
