name: Lint and Format

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint-format:
    name: Biome Lint and Format (check only)
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            ~/.cache/bun
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb', 'bun.lock', 'bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Biome check (lint + format)
        run: bunx @biomejs/biome check --no-errors-on-unmatched --reporter=github .

      - name: Biome format (no write)
        run: bunx @biomejs/biome format --no-errors-on-unmatched --write=false --log-level=info .
